
services:
  front-end:
    environment:
      - DEBUG_MODE=true
    build:
      context: ./next/recette
    ports:
      - "3000:3000"
    volumes:
      - ./next/recette:/app
    command: npm run dev
    depends_on:
      - back-end
    links:
      - back-end
    networks:
      - default

  back-end:
    environment:
      - ANON_KEY=${ANON_KEY_NEXTJS}
      - DATABASE_URL=${DATABASE_URL_NEXTJS}
    build:
      context: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    command: flask --app ./api/index run --debug --host=0.0.0.0
    networks:
      - default

networks:
  default:
      name: NextJsPresentation
