FROM python:3.8-slim


COPY . /app
# Set the working directory
WORKDIR /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

# Expose the port
EXPOSE 5000

# Command to run on container start
CMD [ "python", "api/index.py" ]